#![no_std]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![doc(html_no_source)]

/// Raw bindings generated by `stm32-bindings-gen`.
///
/// The `bindings` module is produced by `bindgen` and exposes a one-to-one FFI
/// surface to the STM32 WBA MAC middleware. All items should be treated as
/// `unsafe` and wrapped by higher-level crates before use.
pub mod bindings;

pub use bindings::*;
